#!/usr/bin/env python3
"""
generate_ctr.py - Generate compile_time_request.c from Klipper data dictionary

Usage: python3 generate_ctr.py atmega328.dict > ../src/compile_time_request.c
"""
import json, zlib, sys, os

# Commands already ported to generic_arduino (handlers exist in basecmd.c/debugcmds.c)
PORTED_COMMANDS = {
    'identify', 'clear_shutdown', 'emergency_stop',
    'get_uptime', 'get_clock', 'get_config', 'finalize_config', 'allocate_oids',
    'debug_read', 'debug_write', 'debug_ping', 'debug_nop',
}

# Commands with HF_IN_SHUTDOWN flag
SHUTDOWN_OK = {'identify', 'clear_shutdown', 'emergency_stop',
               'get_config', 'get_clock', 'get_uptime',
               'debug_read', 'debug_write', 'debug_ping', 'debug_nop'}

def parse_fmt(fmt):
    """Parse format string into list of (PT_type, specifier)."""
    params = []
    i = 0
    while i < len(fmt):
        if fmt.startswith('%.*s', i):
            params.append(('PT_progmem_buffer', '%.*s'))
            i += 4
        elif fmt.startswith('%*s', i):
            params.append(('PT_buffer', '%*s'))
            i += 3
        elif fmt.startswith('%hu', i):
            params.append(('PT_uint16', '%hu'))
            i += 3
        elif fmt.startswith('%hi', i):
            params.append(('PT_int16', '%hi'))
            i += 3
        elif fmt.startswith('%c', i):
            params.append(('PT_byte', '%c'))
            i += 2
        elif fmt.startswith('%u', i):
            params.append(('PT_uint32', '%u'))
            i += 2
        elif fmt.startswith('%i', i):
            params.append(('PT_int32', '%i'))
            i += 2
        else:
            i += 1
    return params

def generate(dict_path, mcu_name=None, mcu_version=None):
    with open(dict_path) as f:
        d = json.load(f)

    cmds = d['commands']   # {fmt: msgid}
    resps = d['responses'] # {fmt: msgid}
    cfg = d.get('config', {})
    consts = d.get('constants', {})
    ver = d.get('version', 'generic_arduino 1.0')

    # Override MCU name from CLI
    if mcu_name:
        cfg['MCU'] = mcu_name
    if mcu_version:
        ver = mcu_version

    L = []
    a = L.append

    a('// compile_time_request.c - auto-generated by generate_ctr.py')
    a('// DO NOT EDIT MANUALLY')
    a('')
    a('#include "command.h"')
    a('#include "sched.h"')
    a('#include "board/pgm.h"')
    a('#include <stddef.h>')
    a('')

    # ── Stub declarations for unported commands ──
    a('// Handlers ported from basecmd.c / debugcmds.c')
    for name in sorted(PORTED_COMMANDS):
        a(f'extern void command_{name}(uint32_t *args);')
    a('')
    a('// Stubs for commands not yet ported')
    unported = [k.split()[0] for k in cmds if k.split()[0] not in PORTED_COMMANDS]
    for name in sorted(set(unported)):
        a(f'extern void command_{name}_stub(uint32_t *args);')
    a('')
    a('extern void sendf_shutdown(void);')
    a('extern void console_task(void);')
    a('extern void timer_task(void);')
    a('')

    # ── Stub implementations ──
    a('// Stub command handlers (port later for full function)')
    a('static uint8_t command_stub_shutdown;')
    for name in sorted(set(unported)):
        a(f'void command_{name}_stub(uint32_t *args) {{ (void)args; }}')
    a('')

    # ── Param type arrays ──
    a('// Parameter type arrays (PROGMEM)')
    ptype_vars = {}  # (tuple of pt_names) -> var_name
    for fmt_list, label in [(cmds, 'cmd'), (resps, 'resp')]:
        for fmt, msgid in fmt_list.items():
            params = parse_fmt(fmt)
            sig = tuple(p[0] for p in params)
            if sig and sig not in ptype_vars:
                vn = f'ptypes_{label}_{msgid}'
                ptype_vars[sig] = vn
                a(f'static const uint8_t {vn}[] PROGMEM = {{')
                for pt, spec in params:
                    a(f'    {pt},  // {spec}')
                a('};')
                a('')
    a('')

    # ── Response encoders ──
    a('// Response encoders (PROGMEM)')
    encoder_map = {}  # fmt -> msgid
    for fmt, msgid in sorted(resps.items(), key=lambda x: x[1]):
        params = parse_fmt(fmt)
        sig = tuple(p[0] for p in params)
        pt_var = ptype_vars.get(sig, 'NULL')
        a(f'// "{fmt}"')
        a(f'static const struct command_encoder enc_r{msgid} PROGMEM = {{')
        a(f'    .encoded_msgid = {msgid},')
        if len(params) == 0:
            a('    .max_size = 5,  // ACK')
        else:
            a('    .max_size = 64,')
        a(f'    .num_params = {len(params)},')
        a(f'    .param_types = {pt_var},')
        a('};')
        a('')
        encoder_map[fmt.split()[0]] = msgid
    a('')

    # ── Command index ──
    a('// Command index (PROGMEM)')
    max_mid = max(cmds.values())
    a(f'const struct command_parser command_index[] PROGMEM = {{')
    for mid in range(max_mid + 1):
        fmt = None
        for f, m in cmds.items():
            if m == mid:
                fmt = f
                break
        if fmt is None:
            a(f'    [{mid}] = {{ .encoded_msgid = {mid}, .num_args = 0, .flags = 0, .num_params = 0, .param_types = NULL, .func = NULL }},')
            continue
        params = parse_fmt(fmt)
        sig = tuple(p[0] for p in params)
        pt_var = ptype_vars.get(sig, 'NULL')
        cmd_name = fmt.split()[0]
        flags = 'HF_IN_SHUTDOWN' if cmd_name in SHUTDOWN_OK else '0'
        if cmd_name in PORTED_COMMANDS:
            fn = f'command_{cmd_name}'
        else:
            fn = f'command_{cmd_name}_stub'
        a(f'    [{mid}] = {{')
        a(f'        .encoded_msgid = {mid},')
        a(f'        .num_args = {len(params)},')
        a(f'        .flags = {flags},')
        a(f'        .num_params = {len(params)},')
        a(f'        .param_types = {pt_var},')
        a(f'        .func = {fn},')
        a('    },')
    a('};')
    a(f'const uint16_t command_index_size PROGMEM = {max_mid + 1};')
    a('')

    # ── Identify data (zlib-compressed JSON) ──
    a('// Identify data dictionary (zlib-compressed JSON, PROGMEM)')
    dd = {
        'commands': {f: m for f, m in sorted(cmds.items(), key=lambda x: x[1])},
        'responses': {f: m for f, m in sorted(resps.items(), key=lambda x: x[1])},
        'config': cfg,
        'constants': consts,
        'app': 'Kalico',
        'version': 'generic_arduino-' + ver,
        'build_versions': '',
    }
    raw = json.dumps(dd, separators=(',', ':'))
    compressed = zlib.compress(raw.encode())
    sz = len(compressed)

    a(f'const uint8_t command_identify_data[] PROGMEM = {{')
    for i in range(0, sz, 12):
        chunk = compressed[i:i+12]
        hexes = ', '.join(f'0x{b:02x}' for b in chunk)
        a(f'    {hexes},')
    a('};')
    a(f'const uint32_t command_identify_size PROGMEM = {sz};')
    a('')

    # ── Encoder lookup ──
    a('// Encoder lookup')
    a('const struct command_encoder *')
    a('ctr_lookup_encoder(const char *str)')
    a('{')
    for fmt, mid in sorted(resps.items(), key=lambda x: x[1]):
        fw = fmt.split()[0]
        a(f'    if (str[0] == \'{fw[0]}\' && !strncmp(str, "{fw}", {len(fw)})) return &enc_r{mid};')
    a('    return &enc_r32; // fallback: "starting" encoder')
    a('}')
    a('')
    a('const struct command_encoder *')
    a('ctr_lookup_output(const char *str) { (void)str; return NULL; }')
    a('')
    a('uint8_t')
    a('ctr_lookup_static_string(const char *str) { (void)str; return 0; }')

    return '\n'.join(L) + '\n'

if __name__ == '__main__':
    import argparse
    p = argparse.ArgumentParser(description='Generate compile_time_request.c')
    p.add_argument('dict', help='Path to .dict file')
    p.add_argument('--mcu-name', '-m', help='Override MCU name in identify response')
    p.add_argument('--version', '-v', help='Override version string')
    args = p.parse_args()
    print(generate(args.dict, mcu_name=args.mcu_name, mcu_version=args.version))
